
kafka:
  bootstrap-servers: 172.25.0.3:29091
  user-events:
    topic: user-events
  disaster-events:
    topic: disaster-events

user-service:
  endpoint: http://192.168.0.111:8090/user-events

disaster-service:
  endpoint: http://192.168.0.111:8090/disasters

notification-service:
  timestamp-gap: 604800000
  coordinates-gap: 0.5

server:
  port: 8080