
kafka:
  bootstrap-servers: 172.25.0.7:29091
  user-events:
    topic: user-events
  disaster-events:
    topic: disaster-events

user-service:
  endpoint: localhost:8002/events

disaster-service:
  endpoint: localhost:8003/events

notification-service:
  timestamp-gap: 1000000000
  coordinates-gap: 90

server:
  port: 8080